### ISSUE TITLE
How I can add new node to elliptics group? (autodiscovery)

### ISSUE THREAD

**Issue by revengel** [reverbrain/elliptics#718]
I have 3 container elliptics:

```yaml
  elliptics11:
    image: "elliptics:latest"
    environment:
      ELLIPTICS_GROUP: 1
      ELLIPTICS_REMOTE_CONNECT: "elliptics12:1025:2;elliptics13:1025:2;"
      ELLIPTICS_ADDRESSES: "elliptics11:1025:2-1"

  elliptics12:
    image: "elliptics:latest"
    environment:
      ELLIPTICS_GROUP: 1
      ELLIPTICS_REMOTE_CONNECT: "elliptics11:1025:2;elliptics13:1025:2"
      ELLIPTICS_ADDRESSES: "elliptics12:1025:2-1"

  elliptics13:
    image: "elliptics:latest"
    environment:
      ELLIPTICS_GROUP: 1
      ELLIPTICS_REMOTE_CONNECT: "elliptics11:1025:2;elliptics12:1025:2"
      ELLIPTICS_ADDRESSES: "elliptics13:1025:2-1"
```

How I can use 'autodiscovery' for quick and easy adding node to the elliptics group?
